# Generated by Django 4.2.14 on 2024-07-21 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Элемент')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(blank=True, default=0, null=True, verbose_name='Калории')),
                ('proteins', models.IntegerField(blank=True, default=0, null=True, verbose_name='Белки')),
                ('fats', models.IntegerField(blank=True, default=0, null=True, verbose_name='Жиры')),
                ('carbohydrates', models.IntegerField(blank=True, default=0, null=True, verbose_name='Углеводы')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Рейтинг')),
                ('rating_num', models.IntegerField(default=0, help_text='Укажите рейтинг элемента от 0 до 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Рейтинг')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Тип элемента')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Продукт')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Изображение')),
                ('category', models.ManyToManyField(to='food.category', verbose_name='Категория')),
                ('element', models.ManyToManyField(to='food.element', verbose_name='Элемент')),
                ('nutrient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.nutrient', verbose_name='КБЖУ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='element',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.rating', verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.ManyToManyField(to='food.type', verbose_name='Тип элемента'),
        ),
    ]
