# Generated by Django 4.2.14 on 2024-07-22 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Цена')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название элемента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_num',
            field=models.IntegerField(default=0, help_text='Укажите рейтинг элемента от 0 до 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название типа элемента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.price', verbose_name='Цена продукта'),
        ),
    ]
