# Generated by Django 4.2.14 on 2024-07-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_price_alter_category_title_alter_element_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='nutrient',
            options={'verbose_name': 'КБЖУ', 'verbose_name_plural': 'КБЖУ'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'цену', 'verbose_name_plural': 'цены'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг элемента', 'verbose_name_plural': 'Рейтинг элементов'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип элемента', 'verbose_name_plural': 'Типы элементов'},
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
