# Generated by Django 4.2.14 on 2024-07-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_category_options_alter_element_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'элемент', 'verbose_name_plural': 'элементы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'рейтинг элемента', 'verbose_name_plural': 'рейтинг элементов'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'тип элемента', 'verbose_name_plural': 'типы элементов'},
        ),
    ]
