# Generated by Django 4.2.14 on 2024-07-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_product_image'),
        ('food', '0004_alter_category_options_alter_element_options_and_more'),
    ]

    operations = [
    ]
