# Generated by Django 4.2.14 on 2024-07-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_merge_20240723_1144'),
        ('food', '0005_merge_20240723_1205'),
    ]

    operations = [
    ]
