# Generated by Django 4.2.14 on 2024-07-23 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_merge_20240723_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='food.nutrient', verbose_name='КБЖУ'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_num',
            field=models.IntegerField(default=0, help_text='Укажите рейтинг элемента от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
