# Generated by Django 4.2.14 on 2024-07-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_product_nutrient_alter_rating_rating_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.rating', verbose_name='Рейтинг'),
        ),
    ]
