# Generated by Django 4.2.14 on 2024-07-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_element_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.price', verbose_name='Цена продукта, ₽'),
        ),
    ]
